### ISSUE TITLE
RuntimeError: The expanded size of the tensor (11) must match the existing size (15) at non-singleton dimension 0.  Target sizes: [11].  Tensor sizes: [15]

### ISSUE THREAD

**Issue by ghost** [AndriyMulyar/semantic-text-similarity#1]
```
>>> model.predict([("he lives in america","he is an indian but stays in america")])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/gitcodes/semantic-text-similarity/semantic_text_similarity/models/bert/similarity.py", line 111, in predict
    [{'sentence_1': s1, 'sentence_2':s2} for s1, s2 in data], self.bert_tokenizer)
  File "/data/gitcodes/semantic-text-similarity/semantic_text_similarity/models/bert/bert_preprocessing.py", line 77, in bert_sentence_pair_preprocessing
    dataset_input_ids[idx] = torch.tensor(input_ids, dtype=torch.long)
RuntimeError: The expanded size of the tensor (11) must match the existing size (15) at non-singleton dimension 0.  Target sizes: [11].  Tensor sizes: [15]
```

**Comment by AndriyMulyar** [comment]
Please provide your entire scripts alongside system specifications.

UPDATE:
This has been fixed. Thank you for reporting the problem

**Comment by ghost** [comment]
No special scripts... Just did pip and ran as shown in code..
I am running on Ubuntu

**Comment by AndriyMulyar** [comment]
Please re-install:

`pip install --upgrade semantic-text-similarity`

**Comment by ghost** [comment]
Thanks.. What was the issue by the way

**Comment by AndriyMulyar** [comment]
A [typo](https://github.com/AndriyMulyar/semantic-text-similarity/blob/master/semantic_text_similarity/models/bert/bert_preprocessing.py#L42) in the BERT pre-processing code that only effected the pre-processing on small batch sizes.
