### ISSUE TITLE
PermissionError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by jrachid** [AndriyMulyar/semantic-text-similarity#10]
Hello,

When I launch your example, the program begins by download we_bert_similarity.tar.gz, and at the end of the download I have the following error:
`Failed to download model: web-bert-similarity
Traceback (most recent call last):
  File "semantic_similarity.py", line 4, in <module>
    web_model = WebBertSimilarity(device='cpu', batch_size=10) #defaults to GPU prediction
  File "F:\Users\rachidj\Anaconda3\envs\nlpenv\lib\site-packages\semantic_text_similarity\models\bert\web_similarity.py", line 7, in __init__
    model_path = get_model_path(model_name)
  File "F:\Users\rachidj\Anaconda3\envs\nlpenv\lib\site-packages\semantic_text_similarity\models\util.py", line 40, in get_model_path
    raise exc
  File "F:\Users\rachidj\Anaconda3\envs\nlpenv\lib\site-packages\semantic_text_similarity\models\util.py", line 36, in get_model_path
    tar = tarfile.open(temp_file.name)
  File "F:\Users\rachidj\Anaconda3\envs\nlpenv\lib\tarfile.py", line 1573, in open
    return func(name, "r", fileobj, **kwargs)
  File "F:\Users\rachidj\Anaconda3\envs\nlpenv\lib\tarfile.py", line 1638, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "F:\Users\rachidj\Anaconda3\envs\nlpenv\lib\gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\rachidj\\AppData\\Local\\Temp\\tmpq6i6wt_s'`

So I downloaded them manually, but I don't know where put them to make the example script working

**Comment by rod08018** [comment]
I have this exacto problem could you get this running?

**Comment by AndriyMulyar** [comment]
The implementation works only on a Linux machine.

**Comment by jaehong-park-78** [comment]
Can you make it work on Windows platform?

**Comment by AndriyMulyar** [comment]
No sorry.

**Comment by TheMarvelousWhale** [comment]
Hi all, 

For this problem, you can download bert pretrained model (*.tar.gz) manually and tweak the get_model_path. Works for me on a Windows 10 machine, with Anaconda. 

Cheers

**Comment by sumanA92** [comment]
Thank you TheMarvelousWhale. I am able to execute web-bert-similarity in windows 10 machine

Suman

**Comment by ibtehajali67** [comment]
> weak the get_model_p

how you give path

**Comment by Firas-al** [comment]
To avoid **PermissionError: [Errno 13] Permission denied:** 

To change the path first install the the folder. Then click on WebBertSimilarity().
![image](https://github.com/AndriyMulyar/semantic-text-similarity/assets/57455809/5773fac1-0555-4b4e-a433-c9d969b8220c)
Then you will get :
![image](https://github.com/AndriyMulyar/semantic-text-similarity/assets/57455809/d8dad1b1-1a20-4e97-a58f-8e0672e486fa)
you should change as the following :
![image](https://github.com/AndriyMulyar/semantic-text-similarity/assets/57455809/c4af0cfb-f1dd-434d-9125-cd15509f461d)
Then run the program : 
![image](https://github.com/AndriyMulyar/semantic-text-similarity/assets/57455809/818f1d2d-23df-4025-bb75-64a948ad2b50)
