### ISSUE TITLE
cant install semantic-test-similarity

### ISSUE THREAD

**Issue by vimal-dharmalingam** [AndriyMulyar/semantic-text-similarity#17]
Collecting semantic-text-similarity
  Using cached semantic_text_similarity-1.0.3-py3-none-any.whl (416 kB)
Collecting pytorch-transformers==1.1.0
  Using cached pytorch_transformers-1.1.0-py3-none-any.whl (158 kB)
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\vdharmalin\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\vdharmalin\\AppData\\Local\\Temp\\pip-install-cnw3ben9\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\vdharmalin\\AppData\\Local\\Temp\\pip-install-cnw3ben9\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\vdharmalin\AppData\Local\Temp\pip-wheel-c1gced_z'
       cwd: C:\Users\vdharmalin\AppData\Local\Temp\pip-install-cnw3ben9\torch\
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\vdharmalin\AppData\Local\Temp\pip-install-cnw3ben9\torch\setup.py", line 225, in <module>
      setup(name="torch", version="0.1.2.post2",
    File "C:\Users\vdharmalin\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\vdharmalin\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\vdharmalin\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\vdharmalin\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\vdharmalin\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')

**Comment by vimal-dharmalingam** [comment]
above is the error im getting

**Comment by Anujay-Saraf** [comment]
Hi Vimal,

Can you try installing with pip , as it's not giving me any error with that

**pip install semantic-text-similarity**

Note: i have fuzzywuzzy, torch, sentence-transformers already installed in my environment.
